version: 1

runtime:
  client:
    storage:
      persistent: true
      path: '/tmp/user-2/dx/cli'

  # TODO(burdon): Configure local kube.
  services:
    ipfs:
      server: 'https://ipfs-pub1.kube.dxos.network'
    signal:
      server: 'wss://demo.kube.dxos.network/dxos/signal'
    ice:
      - urls: 'turn:demo.kube.dxos.network:3478'
        username: 'dxos'
        credential: 'dxos'
