app:
  title: "Tasks App"
system:
  storage:
    persistent: true
services:
  signal:
    server: "wss://apollo3.kube.moon.dxos.network/dxos/signal"
  dxns:
    server: "https://apollo3.kube.moon.dxos.network/dxos/wns/api"
