version: 1

runtime:
  services:
    ipfs:
      server: 'https://ipfs-pub1.kube.dxos.network'
    signal:
      server: 'wss://halo.dxos.org/.well-known/dx/signal'
#     server: 'ws://localhost:9003/.well-known/dx/signal'
    ice:
      - urls: 'turn:demo.kube.dxos.network:3478'
        username: 'dxos'
        credential: 'dxos'
