contact_links:
  - name: Talk to us on Discord
    url: https://dxos.org/discord
    about: General questions, feedback, and discussion
  - name: Report a security vulnerability
    url: mailto:security@dxos.org
    about: Please report security vulnerabilities here.
