version: 1

runtime:
  client:
    storage:
      persistent: true
      path: '/tmp/dxos/dx-cli/user-2'

  services:
    ipfs:
      server: 'https://ipfs-pub1.kube.dxos.network'
    signal:
      server: 'ws://localhost:8888/.well-known/dx/signal'
    ice:
      - urls: 'turn:demo.kube.dxos.network:3478'
        username: 'dxos'
        credential: 'dxos'
