version: 1

runtime:
  client:
    storage:
      persistent: true
      path: /tmp/dx/cli

  services:
    ipfs:
      server: http://localhost:5001/
      gateway: http://localhost:8888/ipfs
    signal:
      server: ws://localhost:9002/.well-known/dx/signal
    ice:
      - urls: turn:localhost:3478
        username: dxos
        credential: dxos
    publisher:
      server: ws://localhost:9002/.well-known/dx/deploy
