version: 1

runtime:
  client:
    storage:
      persistent: true
      path: '/tmp/dx/cli'

  services:
    ipfs:
      server: "http://kube.dxos.org:5001/"
      gateway: "http://kube.dxos.org:8888/ipfs"
    signal:
      server: 'wss://kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'turn:kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
    publisher:
      server: ws://127.0.0.1:9002/.well-known/dx/deploy
    machine:
      doAccessToken: ''
