version: 1

runtime:
  client:
    storage:
      persistent: true
      path: /tmp/dx/cli


  services:
    signal:
      - server: ws://localhost/.well-known/dx/signal
    ice:
      - urls: stun:kube.dxos.org:3478
        username: dxos
        credential: dxos
      - urls: turn:kube.dxos.org:3478
        username: dxos
        credential: dxos
      - urls: stun:dev.kube.dxos.org:3478
      - urls: turn:dev.kube.dxos.org:3478
        username: dxos
        credential: dxos
    ipfs:
      server: http://localhost:5001/api/v0
      gateway: http://localhost:8080/ipfs
    publisher:
      server: ws://127.0.0.1/.well-known/dx/deploy
    supervisor:
      server: ws://127.0.0.1/.well-known/dx/supervisor
    machine:
      doAccessToken: ''
