#
# Pages Functions configuration.
# https://developers.cloudflare.com/pages/functions/wrangler-configuration
#

name = "dxos-storybook"
compatibility_date = "2024-04-05"
pages_build_output_dir = "./out/stories"

#
# Dev
# http://localhost:8788
# moon run storybook:bundle
# wrangler pages dev
#
# Prod is pushed via GH Actions CI.
# wrangler pages deploy out/stories
# https://dxos-storybook.pages.dev
#
