$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  pack:
    script: pnpm pack --pack-destination "$(git rev-parse --show-toplevel)/dist/tarballs/$project"
    deps:
      - target: build
        optional: true
      - target: compile
        optional: true
    inputs:
      - '@group(production)'
    outputs:
      - /dist/tarballs/$project

inheritedBy:
  tags: pack
