$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  build:
    command: pnpm exec tsc --noEmit
    deps:
      - ^:build
      - ^:compile
    inputs:
      - /tsconfig.base.json
      - tsconfig.json
      - '@group(sources)'
    options:
      timeout: 60
