$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  compile:
    command: pnpm exec dx-build
    deps:
      - dx-build:compile
      - ^:compile
      - ^:build
    inputs:
      - /tsconfig.base.json
      - tsconfig.json
      - '@group(production)'
    outputs:
      - dist/
    options:
      timeout: 60
