$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  lint:
    command: pnpm exec eslint . --format unix --quiet
    inputs:
      - /eslint.config.mjs
      # Is this fine:
      - /tools/eslint-plugin-rules/**/*
      - '@group(sources)'
