layer: application
language: typescript
tags:
  - typecheck
  - vite
tasks:
  compile:
    command: echo "No compilation needed for vite application"
    outputs: []
    options:
      merge: replace
  bundle:
    deps:
      - shell:bundle

  serve:
    deps:
      - shell:bundle
