version: 1
stateMachine: "test-host"
startSequence:
  commands:
    - createProfile:
        _nop_: true
testSequences:
  - commands:
    - createSpace:
        id: "space-1"
    - createSpaceInvitation:
        id: "space-1"
        swarmKey: "62815fecc2448f37aab2b77c92f5a73a238407d8eb3ff15eeb4037bda4c075ae"
    - syncServer:
        id: "gravity-agent-server-sync"
        msg: "client-alive-ready"
stopSequence:
  commands:
    - tearDown:
        _nop_: true

