name: Build and Publish Docker Container for CircleCI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - nf/circleci-docker
    paths:
      - .circleci/Dockerfile
      - .github/workflows/circleci_docker_image.yml #shouldn't be needed, but it seems to be?
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/dxos/circleci-node
  DEFAULT_NODE_VERSION: 18.19.0

jobs:
  build_and_publish_matrix:
    strategy:
      matrix:
        node_version: [ "18.19.0", "20.10.0", "21.4.0" ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          if [[ "${NODE_VERSION}" = "${DEFAULT_NODE_VERSION}" ]]; then
            docker buildx build --push --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}-${NODE_VERSION}:latest -t ${IMAGE_NAME}:latest .circleci
          else
            docker buildx build --push --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}-${NODE_VERSION}:latest .circleci
          fi
        env:
          NODE_VERSION: ${{ matrix.node_version }}
