name: Build and Publish Docker Container for CircleCI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - nf/circleci-docker
    paths:
      - .circleci/Dockerfile
      - .github/workflows/circleci_docker_image.yml #shouldn't be needed, but it seems to be?
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/dxos/circleci-node
  DEFAULT_NODE_VERSION: 20.12.1
  IMAGE_TAG_SUFFIX: ""

jobs:
  build_and_publish_matrix:
    strategy:
      matrix:
        node_version: [ "18.20.1", "20.12.1", "21.7.2" ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set suffix if on branch
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/main" ]]; then
            BRANCH=${GITHUB_REF#refs/heads/}
            echo "IMAGE_TAG_SUFFIX=-${BRANCH//\//-}" >> $GITHUB_ENV
          fi
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          if [[ "${NODE_VERSION}" = "${DEFAULT_NODE_VERSION}" ]]; then
            docker buildx build --push --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}:${NODE_VERSION}${IMAGE_TAG_SUFFIX} -t ${IMAGE_NAME}:latest .circleci
            docker buildx build --push --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}-go:${NODE_VERSION} -f .circleci/Dockerfile-go .circleci
          else
            docker buildx build --push --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}:${NODE_VERSION}${IMAGE_TAG_SUFFIX} .circleci
          fi
        env:
          NODE_VERSION: ${{ matrix.node_version }}
