on:
 schedule:
   - cron: '*/10 * * * *'

name: Upgrade DXOS dependencies
jobs:
 upgrade:
   name: Upgrade DXOS dependencies
   runs-on: ubuntu-latest
   timeout-minutes: 5
   steps:
     - name: Upgrade DXOS dependencies
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           npx @dxos/version-check upgrade --scope @dxos --tilde
           yarn install
         COMMIT_MESSAGE: 'fix: Upgrade DXOS dependencies'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'example@example.com'
         PR_BRANCH_NAME: 'chore-deps-update-${PR_ID}'
         PR_TITLE: 'fix: Upgrade DXOS dependencies'
         GITHUB_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
