on:
  push:
    branches:
      - release
name: release - Publish to NPM
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build and NPM publish
        run: |
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DXOS"
          yarn install --frozen-lockfile
          yarn lint:lockfile
          yarn lint
          yarn build
          yarn test
          git reset --hard
          VERSION=`cat package.json | grep '"version":' | awk '{ print $2 }' | sed 's/[",]//g'`
          yarn lerna version $VERSION --no-git-tag-version -y
          git commit -am "v$VERSION"
          git push
          git tag -f "v$VERSION"
          git push --tags -f
          yarn lerna publish from-package --force-publish -y
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
