on:
  push:
    branches:
      - release
name: release - Publish to NPM on merged release PR
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: dxos/release-please-action@v0.0.100
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@dxos/sdk'
          default-branch: release
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Build and Publish to NPM
        run: |
          #npm whoami
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DXOS"
          yarn
          yarn build
          yarn lint
          yarn test
          git reset --hard
          yarn lerna version `echo "${{ steps.release.outputs.tag_name }}" | sed 's/^v//'` --no-git-tag-version -y
          git commit -am "${{ steps.release.outputs.tag_name }}"
          git push
          git tag -f "${{ steps.release.outputs.tag_name }}"
          git push --tags -f
          yarn lerna publish from-package --force-publish -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
